// Global using directives
global using BattleNetPrefill.Utils.Debug;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Security.Cryptography;
global using System.Text;
global using System.Threading.Tasks;
global using ByteSizeLib;
global using LancachePrefill.Common.Extensions;
global using LeagueToolkit.IO.ReleaseManifestFile;
global using RiotPrefill.Models;
global using Spectre.Console;
global using static LancachePrefill.Common.SpectreFormatters;
global using AnsiConsoleExtensions = LancachePrefill.Common.Extensions.AnsiConsoleExtensions;
global using System.Collections.Concurrent;
global using System.Net.Http.Headers;
global using LancachePrefill.Common;
global using LancachePrefill.Common.Enums;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Threading.Tasks;
global using RiotPrefill.Debug;
global using RiotPrefill.Handlers;
global using System.Net.Http;
global using RiotPrefill.Models;
global using RiotPrefill.Settings;
global using System.Text.RegularExpressions;
global using Intellenum;
global using JetBrains.Annotations;
global using System.Threading;